### ISSUE TITLE
Notification sync

### ISSUE THREAD

**Issue by puppet680** [srilakshmikanthanp/clipbirdroid#3]
I Want to add notification bar synchronization

**Comment by srilakshmikanthanp** [comment]
Thank you for your suggestion! Currently, our focus is on syncing clipboard data. We'll take some time to discuss the possibility of adding notification bar synchronization and will keep you updated.

**Comment by srilakshmikanthanp** [comment]
Meanwhile, you can take a look at existing solutions like [kde connect](https://kdeconnect.kde.org/), [Microsoft Phone Link](https://www.microsoft.com/en-in/windows/sync-across-your-devices).

**Comment by srilakshmikanthanp** [comment]
Thanks for your time and suggestion. After discussion, we planned not to implement this feature since it is beyond the scope of the project. So I am closing this Issue as won't be fixed. if we have any plans for this feature we will let you know :)

**Comment by srilakshmikanthanp** [comment]
Thank you for your time and suggestion. Following our discussion, we have decided not to implement this feature as it falls outside the scope of the project. Therefore, I am closing this issue as "won't be fixed." If there are any future plans regarding this feature, we will keep you informed. :)
