### ISSUE TITLE
Optimization suggestions

### ISSUE THREAD

**Issue by puppet680** [srilakshmikanthanp/clipbirdroid#4]
Proposal: Can a transparent floating window be used to gain focus and access the clipboard content? How can we incorporate this functionality?

Enhancement: When clicking on "send clipboard," is it possible for the window to return to the previous app instead of remaining within the current app?

**Comment by srilakshmikanthanp** [comment]
> Proposal: Can a transparent floating window be used to gain focus and access the clipboard content? How can we incorporate this functionality?

Do you mean to access the system clipboard content? A Little explanation with a use case would be better.

> Enhancement: When clicking on "send clipboard," is it possible for the window to return to the previous app instead of remaining within the current app?

There are two ways to send clipboard content,

1. The first one is Inside the Application History page upon clicking it just syncs the clipboard content across devices.
> Note: No screens are changed.
2. The second one is available on the notification bar upon clicking it, it will sync and close the notification drawer.
> Note: I think it should meet your needs.
<img src="https://github.com/srilakshmikanthanp/clipbirdroid/assets/56999577/23c55447-6deb-48bc-9673-aa0178ea93bd" width="200" height="400" />

**Comment by puppet680** [comment]
Test device:
1.Samsung note20 u
2.Lg v60

Clicking on the notification bar will stay in clipbirdroid.

Example：
After I clicked Send Clipboard on the Douyin notification bar, it did not return to the Douyin interface, but stayed in clipbirdroid app.

Ideal：
Return to Douyin program

**Comment by srilakshmikanthanp** [comment]
Thanks for the Information can you give the version of clipbird you are using?

**Comment by puppet680** [comment]
clipbirdroid 1.1.1

**Comment by srilakshmikanthanp** [comment]
Thanks for the Info will check and update, Also I want to ask something,

1. In clipbird 1.1.1 the send button is small so you may clicked the notification itself, and it will open the clipbird app. I will change the send button UI style in the upcoming version as shown in the above image
2. In case you correctly touched the send button did you see the synced toast notification?

**Comment by puppet680** [comment]
Very sure that the button was clicked and the toast was returned

**Comment by srilakshmikanthanp** [comment]
Thanks for your quick reply Can you provide Screenshots or GIFs if possible. It will test via emulator and try to update soon, Thanks :)

**Comment by puppet680** [comment]
https://github.com/srilakshmikanthanp/clipbirdroid/assets/54428441/b478d876-9f58-477d-81cf-78393764a096

**Comment by srilakshmikanthanp** [comment]
It seems like a bug will try to fix to soon, Thanks for your support :)

**Comment by srilakshmikanthanp** [comment]
Can you retry by removing the app from the recent, As far as I tried the App is opened if it is kept in recent if not just works as expected.

**Comment by srilakshmikanthanp** [comment]
Since beginning with Android 10 you can't get the clipboard content without the activity in focus, So I will show the transparent activity with a circular progress Indicator once the window is in focus I will get the content then close it (I think the problem starts here opening activity is unavoidable). I will look for some solutions if I found will keep you updated, Thanks.

**Comment by puppet680** [comment]
Thank you very much. This problem was solved after closing the background.
